implement "--init" option.

diff --git a/exe/git-cococo b/exe/git-cococo
--- a/exe/git-cococo
+++ b/exe/git-cococo
@@ -40,9 +40,40 @@ escape_command_line() {
   done
 }
 
+git_cococo_options() {
+  test -z "$init" || echo_n '--init '
+}
+
 create_commit_message() {
   echo_n 'run: git cococo '
+  git_cococo_options
   escape_command_line "$@"
+}
+
+die_if_both_autostash_and_init() {
+  test -n "$autostash" -a -n "$init" || return 0
+
+  echo 'Cannot use both "--autostash" option and "--init" option.'
+  exit 1
+}
+
+run_git_init_if_init_mode() {
+  test -n "$init" || return 0
+
+  d="$init/.git"
+  if test -e "$d"
+  then
+    cat <<EOF
+"$d" is already exists.
+
+Run without "--init" option:
+
+  $ git cococo $(escape_command_line "$@")
+EOF
+    exit 1
+  fi
+
+  git init --quiet
 }
 
 die_or_autostash_if_uncommitted_changes_are_exists() {
@@ -95,11 +126,15 @@ pop_stash_if_autostashed() {
 main() {
   # parse git cococo options.
   autostash=
+  init=
   while :
   do
     case "$1" in
       --autostash)
         autostash=1
+        ;;
+      --init)
+        init=.
         ;;
       -h|--help)
         echo_n "$USAGE"
@@ -119,7 +154,9 @@ main() {
     esac
     shift
   done
+  die_if_both_autostash_and_init
 
+  run_git_init_if_init_mode "$@"
   die_or_autostash_if_uncommitted_changes_are_exists "$@"
   "$@" # run command.
   commit_uncommitted_changes "$@"
